/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdlib.h>
/* Header for class com_demon_yu_lib_gaussian_StudentNative */

#ifndef _Included_com_demon_yu_lib_gaussian_StudentNative
#define _Included_com_demon_yu_lib_gaussian_StudentNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_demon_yu_lib_gaussian_StudentNative
 * Method:    setStudentAge
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_demon_yu_lib_gaussian_StudentNative_setStudentAge
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_demon_yu_lib_gaussian_StudentNative
 * Method:    releaseStudent
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_demon_yu_lib_gaussian_StudentNative_releaseStudent
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_demon_yu_lib_gaussian_StudentNative
 * Method:    createStudent
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_demon_yu_lib_gaussian_StudentNative_createStudent
  (JNIEnv *, jobject);


JNIEXPORT jlong JNICALL Java_com_demon_yu_lib_gaussian_StudentNative_mallocMemory
        (JNIEnv *, jclass ,jint);

JNIEXPORT void JNICALL Java_com_bytedance_Test_crash
        (JNIEnv *, jclass);


#ifdef __cplusplus
}
#endif
#endif
