/* DO NOT EDIT THIS FILE - it is machine generated */
#include "com_demon_yu_lib_gaussian_GaussianHelper.h"
#include "gaussian_logger.h"
/* Header for class com_demon_yu_lib_gaussian_GaussianHelper */
#include <jni.h>
static const char* TAG="GaussianHelper";

JNIEXPORT void JNICALL Java_com_demon_yu_lib_gaussian_GaussianHelper_blur
  (JNIEnv * env, jclass jclass, jobject jobject){
    __x_debug_log(TAG,"call blur from java");
}
