/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_demon_yu_lib_gaussian_GaussianHelper */

#ifndef _Included_com_demon_yu_lib_gaussian_GaussianHelper
#define _Included_com_demon_yu_lib_gaussian_GaussianHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_demon_yu_lib_gaussian_GaussianHelper
 * Method:    blur
 * Signature: (Landroid/graphics/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_com_demon_yu_lib_gaussian_GaussianHelper_blur
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_demon_yu_lib_gaussian_GaussianHelper
 * Method:    createStudent
 * Signature: ()I
 */
JNIEXPORT jlong JNICALL Java_com_demon_yu_lib_gaussian_GaussianHelper_createStudent
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
