/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_demon_yu_lib_gausiia_Guassia */

#ifndef _Included_com_demon_yu_lib_gausiia_Guassia
#define _Included_com_demon_yu_lib_gausiia_Guassia
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_demon_yu_lib_gausiia_Guassia
 * Method:    guassia
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_demon_yu_lib_gausiia_Guassia_guassia
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
