/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_demon_yu_avd_WebVadHelper */

#ifndef _Included_com_demon_yu_avd_WebVadHelper
#define _Included_com_demon_yu_avd_WebVadHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_demon_yu_avd_WebVadHelper
 * Method:    testVad
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_demon_yu_avd_WebVadHelper_testVad
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
