/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <android/log.h>
/* Header for class com_demon_yu_avd_WebVadHelper */

#ifndef _Included_com_demon_yu_avd_WebVadHelper
#define _Included_com_demon_yu_avd_WebVadHelper

#define LOGI(...) ((void)__android_log_print(ANDROID_LOG_INFO, "gaussian:", __VA_ARGS__))
#define LOGD(...) ((void)__android_log_print(ANDROID_LOG_DEBUG, "gaussian:", __VA_ARGS__))
#define LOGE(...) ((void)__android_log_print(ANDROID_LOG_INFO, "gaussian:", __VA_ARGS__))

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_demon_yu_avd_WebVadHelper
 * Method:    nativeCreateWebVad
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_demon_yu_avd_WebVadHelper_nativeCreateWebVad
  (JNIEnv *, jobject);

/*
 * Class:     com_demon_yu_avd_WebVadHelper
 * Method:    nativeInitWebVad
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_demon_yu_avd_WebVadHelper_nativeInitWebVad
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_demon_yu_avd_WebVadHelper
 * Method:    nativeSetModel
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_demon_yu_avd_WebVadHelper_nativeSetModel
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_demon_yu_avd_WebVadHelper
 * Method:    nativeProcess
 * Signature: (JI[FJ)I
 */
JNIEXPORT jint JNICALL Java_com_demon_yu_avd_WebVadHelper_nativeProcess
  (JNIEnv *, jobject, jlong, jint, jshortArray , jlong);

/*
 * Class:     com_demon_yu_avd_WebVadHelper
 * Method:    nativeRelease
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_demon_yu_avd_WebVadHelper_nativeRelease
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_demon_yu_avd_WebVadHelper
 * Method:    nativeValidRateAndFrameLength
 * Signature: (IJ)I
 */
JNIEXPORT jint JNICALL Java_com_demon_yu_avd_WebVadHelper_nativeValidRateAndFrameLength
  (JNIEnv *, jclass, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
